; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; TEST ENVIRONMENTS

[env:test_codec]
platform = native
test_framework = unity
build_flags =
    -std=gnu++17
    -D NATIVE_TEST
    ; -D EZMODBUS_DEBUG
    -include test/test_codec/mock/ModbusDebug.h
    -I src
test_filter = test_codec
build_src_filter = 
    +<*>
    +<../test/test_codec/*> 

[env:test_rtu_server_loopback]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
test_framework = unity
lib_deps = 
    symlink://.
build_flags = 
    ; -D EZMODBUS_DEBUG
    ; -fstack-usage
test_filter = test_rtu_server_loopback
build_src_filter = 
    +<*>
    +<../test/test_rtu_server_loopback/*> 

[env:test_rtu_client_loopback]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
test_framework = unity
lib_deps =
    symlink://.
build_flags =
    ; -D EZMODBUS_DEBUG
    ; -fstack-usage
test_filter = test_rtu_client_loopback
build_src_filter =
    +<*>
    +<../test/test_rtu_client_loopback/*>

[env:test_rtu_client_loopback_lpuart]
platform = espressif32
board = esp32-c6-devkitm-1
framework = arduino
test_framework = unity
lib_deps =
    symlink://.
build_flags =
    ; -D EZMODBUS_DEBUG
    ; -D EZMODBUS_LOG_Q_SIZE=64
    ; -fstack-usage
    ; ESP32C6 specific config - Uses LPUART for Server side
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -D MBT_UART_NUM=LP_UART_NUM_0
    -D UART_BAUD_RATE=115200
    ; -D EZMODBUS_HAL_UART_LP_SCLK=LP_UART_SCLK_XTAL_D2
    -D EZM_RX=21
    -D EZM_TX=22
    -D MBT_RX=4
    -D MBT_TX=5
    -D MBT_DE=3
test_filter = test_rtu_client_loopback
build_src_filter =
    +<*>
    +<../test/test_rtu_client_loopback/*>

[env:test_tcp_client_loopback]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
test_framework = unity
lib_deps =
    symlink://.
build_flags =
    ; -D EZMODBUS_DEBUG
    ; -fstack-usage
test_filter = test_tcp_client_loopback
build_src_filter = 
    +<*>
    +<../test/test_tcp_client_loopback/*> 

[env:test_bridge_loopback]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
test_framework = unity
lib_deps = 
    symlink://.
build_flags = 
    ; -D EZMODBUS_DEBUG
    ; -fstack-usage
test_filter = test_bridge_loopback
build_src_filter = 
    +<*>
    +<../test/test_bridge_loopback/*> 