site_name: EZModbus Docs

theme:
  name: material
  palette:
    scheme: slate
    primary: blue grey
    accent: blue grey

  font:
    text: Fira Sans
    code: Fira Code
  
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.follow
    - search.highlight
    - search.share
    - content.code.copy
    - content.tabs.link

extra_css:
  - 99-stylesheets/extra.css

nav:
  - Welcome: README.md
  - Getting Started:
    - Introduction: 10-getting-started/100-introduction.md
    - Installation: 10-getting-started/101-installation.md
    - Quick Start Guide: 10-getting-started/102-quick-start-guide.md
  - Core Concepts:
    - Library overview: 20-core-concepts/200-library-overview.md
    - Modbus protocol features: 20-core-concepts/201-modbus-protocol-features.md
    - "Modbus::Frame": 20-core-concepts/202-frame-client.md
    - "Modbus::Word": 20-core-concepts/203-modbus-word.md
    - Error handling: 20-core-concepts/204-error-handling.md
    - HAL wrappers: 20-core-concepts/205-hal-wrappers.md
  - How-To Guides:
    - Modbus Client (Master): 30-how-to-guides/300-modbus-client-master.md
    - Modbus Server (Slave): 30-how-to-guides/301-modbus-server-slave.md
    - Modbus Bridge: 30-how-to-guides/302-modbus-bridge.md
    - Coupling Modbus components: 30-how-to-guides/303-coupling-modbus-components.md
    - API reference: 30-how-to-guides/399-api-reference.md
  - Additional Resources:
    - Examples: 40-additional-resources/400-examples.md
    - Settings (compile flags): 40-additional-resources/401-settings-compile-flags.md
    - Memory & system resources: 40-additional-resources/402-memory-and-system-resources.md
    - Testing: 40-additional-resources/403-testing.md
    - Logging/debugging: 40-additional-resources/404-logging-debugging.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3
  